name: CI

on:
  push:
    branches: [feature/ngrx-signals]
  pull_request:
    branches: [feature/ngrx-signals]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.12.0'
      - name: Install dependencies
        run: npm ci -f
      - name: Lint
        run: npm run lint --if-present
      # - name: Test
      #   run: npm test --silent
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular21demo/browser
